#
# .psd1 file auto-generated by Pode
#
@{
  Web = @{
    TransferEncoding = @{
      Routes = @{}
    }
    OpenApi = @{
      DefaultDefinitionTag = "default"
    }
    Static = @{
      Cache = @{
        Enable = $True
        Include = "*.jpg"
        MaxAge = 15
      }
      Defaults = @(
        "index.html"
        "default.html"
      )
    }
    ErrorPages = @{
      StrictContentTyping = $True
      Default = "application/html"
      Routes = @{
        "/john" = "application/json"
      }
      ShowExceptions = $True
    }
    Compression = @{
      Enabled = $False
    }
    ContentType = @{
      Routes = @{}
    }
  }
  Server = @{
    AutoImport = @{
      Snapins = @{
        Enable = $True
      }
      SecretVaults = @{
        SecretManagement = @{
          ExportOnly = $True
          Enable = $True
        }
      }
      Modules = @{
        ExportOnly = $True
        Enable = $True
      }
      Functions = @{
        ExportOnly = $True
        Enable = $True
      }
    }
    Debug = @{
      Breakpoints = @{
        Enable = $True
      }
    }
    ReceiveTimeout = 100
    Request = @{
      Timeout = 30
      BodySize = 104857600
    }
    DefaultFolders = @{
      Errors = "errors"
      Public = "public"
      Views = "views"
    }
    Ssl = @{
      Protocols = 3120
    }
    Logging = @{
      Masking = @{
        Mask = "--MASKED--"
        Patterns = @(
          "(?<keep_before>Password=)\w+"
          "(?<keep_before>AppleWebKit\/)\d+\.\d+(?(<keep_after)\s+\(KHTML)"
        )
      }
    }
    FileMonitor = @{
      ShowFiles = $True
    }
  }
}
