#
# .psd1 file auto-generated by Pode
#
@{
  Server = @{
    DefaultFolders = @{
      Views = "views"
      Public = "public"
      Errors = "errors"
    }
    FileMonitor = @{
      ShowFiles = $True
    }
    Root = "C:\Users\m_dan\Documents\GitHub\Pode\examples"
    Request = @{
      BodySize = 104857600
      Timeout = 30
    }
    AutoImport = @{
      Modules = @{
        Enable = $True
        ExportOnly = $True
      }
      SecretVaults = @{
        SecretManagement = @{
          Enable = $True
          ExportOnly = $True
        }
      }
      Functions = @{
        Enable = $True
        ExportOnly = $True
      }
      Snapins = @{
        Enable = $True
      }
    }
    Debug = @{
      Breakpoints = @{
        Enable = $True
      }
    }
    Logging = @{
      Masking = @{
        Mask = "--MASKED--"
        Patterns = @(
          "(?<keep_before>Password=)\w+"
          "(?<keep_before>AppleWebKit\/)\d+\.\d+(?(<keep_after)\s+\(KHTML)"
        )
      }
    }
  }
  Web = @{
    TransferEncoding = @{
      Routes = @{}
    }
    ContentType = @{
      Routes = @{}
    }
    Static = @{
      Defaults = @(
        "index.html"
        "default.html"
      )
      Cache = @{
        Enable = $True
        Include = "*.jpg"
      }
    }
    ErrorPages = @{
      StrictContentTyping = $True
      Default = "application/html"
      ShowExceptions = $True
      Routes = @{
        "/john" = "application/json"
      }
    }
  }
}
