#
# Module manifest for module 'Pode'
#
# Generated by: Matthew Kelly (Badgerati)
#
# Generated on: 28/11/2017
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'Pode.psm1'

    # Version number of this module.
    ModuleVersion = '0.0.1'

    # ID used to uniquely identify this module
    GUID = 'e3ea217c-fc3d-406b-95d5-4304ab06c6af'

    # Author of this module
    Author = 'Matthew Kelly (Badgerati)'

    # Copyright statement for this module
    Copyright = 'Copyright (c) 2017-2019 Matthew Kelly (Badgerati), licensed under the MIT License.'

    # Description of the functionality provided by this module
    Description = 'A Cross-Platform PowerShell framework for creating web servers to host REST APIs and Websites. Pode also has support for being used in Azure Functions and AWS Lambda.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '3.0'

    RequiredAssemblies = @(
        # before I could make a WebHostBuilder I needed these
        "./bin/nuget/Microsoft.AspNetCore.2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.dll"
        "./bin/nuget/Microsoft.AspNetCore.Hosting.2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Hosting.dll"
        "./bin/nuget/Microsoft.AspNetCore.Hosting.Abstractions.2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Hosting.Abstractions.dll"
        "./bin/nuget/Microsoft.Extensions.Hosting.Abstractions.2.2.0/lib/netstandard2.0/Microsoft.Extensions.Hosting.Abstractions.dll"
        "./bin/nuget/Microsoft.Extensions.DependencyInjection.Abstractions.2.2.0/lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll"
        "./bin/nuget/Microsoft.Extensions.Configuration.Abstractions.2.2.0/lib/netstandard2.0/Microsoft.Extensions.Configuration.Abstractions.dll"
        "./bin/nuget/Microsoft.Extensions.FileProviders.Abstractions.2.2.0/lib/netstandard2.0/Microsoft.Extensions.FileProviders.Abstractions.dll"
        "./bin/nuget/Microsoft.Extensions.Configuration.EnvironmentVariables.2.2.4/lib/netstandard2.0/Microsoft.Extensions.Configuration.EnvironmentVariables.dll"
        "./bin/nuget/Microsoft.Extensions.Configuration.2.2.0/lib/netstandard2.0/Microsoft.Extensions.Configuration.dll"
        "./bin/nuget/Microsoft.Extensions.Primitives.2.2.0/lib/netstandard2.0/Microsoft.Extensions.Primitives.dll"

        # before it would .build() I needed these
        "./bin/nuget/Microsoft.AspNetCore.Server.Kestrel.Core.2.2.0/lib/netcoreapp2.1/Microsoft.AspNetCore.Server.Kestrel.Core.dll"
        "./bin/nuget/Microsoft.AspNetCore.Server.Kestrel.2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.dll"
        "./bin/nuget/Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll"
        "./bin/nuget/Microsoft.Extensions.Configuration.FileExtensions.2.2.0/lib/netstandard2.0/Microsoft.Extensions.Configuration.FileExtensions.dll"
        "./bin/nuget/Microsoft.AspNetCore.Hosting.Server.Abstractions.2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Hosting.Server.Abstractions.dll"
        "./bin/nuget/Microsoft.AspNetCore.Http.Features.2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Http.Features.dll"
        "./bin/nuget/Microsoft.Extensions.Logging.Abstractions.2.2.0/lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.dll"
        "./bin/nuget/Microsoft.Extensions.Logging.2.2.0/lib/netstandard2.0/Microsoft.Extensions.Logging.dll"
        "./bin/nuget/Microsoft.Extensions.Logging.Configuration.2.2.0/lib/netstandard2.0/Microsoft.Extensions.Logging.Configuration.dll"
        "./bin/nuget/Microsoft.Extensions.Logging.Debug.2.2.0/lib/netstandard2.0/Microsoft.Extensions.Logging.Debug.dll"
        "./bin/nuget/Microsoft.Extensions.Logging.Console.2.2.0/lib/netstandard2.0/Microsoft.Extensions.Logging.Console.dll"
        "./bin/nuget/Microsoft.Extensions.DependencyInjection.2.2.0/lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.dll"
        "./bin/nuget/Microsoft.AspNetCore.Http.Abstractions.2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Http.Abstractions.dll"
        "./bin/nuget/Microsoft.AspNetCore.Http.2.2.2/lib/netstandard2.0/Microsoft.AspNetCore.Http.dll"
        "./bin/nuget/Microsoft.Extensions.Options.2.2.0/lib/netstandard2.0/Microsoft.Extensions.Options.dll"
        "./bin/nuget/Microsoft.Extensions.ObjectPool.2.2.0/lib/netstandard2.0/Microsoft.Extensions.ObjectPool.dll"
        "./bin/nuget/Microsoft.Extensions.FileProviders.Physical.2.2.0/lib/netstandard2.0/Microsoft.Extensions.FileProviders.Physical.dll"
        "./bin/nuget/Microsoft.Extensions.FileProviders.Composite.2.2.0/lib/netstandard2.0/Microsoft.Extensions.FileProviders.Composite.dll"
        "./bin/nuget/Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.2.2.1/lib/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll"
        "./bin/nuget/Microsoft.AspNetCore.Diagnostics.Abstractions.2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Diagnostics.Abstractions.dll"
        "./bin/nuget/Microsoft.AspNetCore.Diagnostics.2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Diagnostics.dll"
        "./bin/nuget/Microsoft.AspNetCore.Http.Extensions.2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Http.Extensions.dll"
        "./bin/nuget/Microsoft.AspNetCore.HttpOverrides.2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.HttpOverrides.dll"
        "./bin/nuget/Microsoft.AspNetCore.Routing.Abstractions.2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Routing.Abstractions.dll"
        "./bin/nuget/Microsoft.AspNetCore.Routing.2.2.2/lib/netstandard2.0/Microsoft.AspNetCore.Routing.dll"
        "./bin/nuget/Microsoft.AspNetCore.Server.IISIntegration.2.2.1/lib/netstandard2.0/Microsoft.AspNetCore.Server.IISIntegration.dll"
        "./bin/nuget/Microsoft.AspNetCore.Server.Kestrel.Https.2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Https.dll"
        "./bin/nuget/Microsoft.AspNetCore.WebUtilities.2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.WebUtilities.dll"
        "./bin/nuget/Microsoft.Extensions.Configuration.Binder.2.2.4/lib/netstandard2.0/Microsoft.Extensions.Configuration.Binder.dll"
        "./bin/nuget/Microsoft.Extensions.Configuration.Json.2.2.0/lib/netstandard2.0/Microsoft.Extensions.Configuration.Json.dll"
        "./bin/nuget/Microsoft.Extensions.FileSystemGlobbing.2.2.0/lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll"
        "./bin/nuget/Microsoft.Extensions.Logging.Console.2.2.0/lib/netstandard2.0/Microsoft.Extensions.Logging.Console.dll"
        "./bin/nuget/Microsoft.Extensions.Options.ConfigurationExtensions.2.2.0/lib/netstandard2.0/Microsoft.Extensions.Options.ConfigurationExtensions.dll"
        "./bin/nuget/Microsoft.Net.Http.Headers.2.2.0/lib/netstandard2.0/Microsoft.Net.Http.Headers.dll"
        "./bin/nuget/Microsoft.Extensions.FileProviders.Embedded.2.2.0/lib/netstandard2.0/Microsoft.Extensions.FileProviders.Embedded.dll"

        # In order to configure static files, we needed...
        "./bin/nuget/Microsoft.AspNetCore.StaticFiles.2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.StaticFiles.dll"
        "./bin/nuget/Microsoft.Extensions.WebEncoders.2.2.0/lib/netstandard2.0/Microsoft.Extensions.WebEncoders.dll"

        # In order to .Start() we needed...
        "./bin/nuget/System.IO.Pipelines.4.5.2/lib/netstandard2.0/System.IO.Pipelines.dll"
        "./bin/nuget/Microsoft.AspNetCore.Connections.Abstractions.2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Connections.Abstractions.dll"
    )

    # Functions to export from this Module
    FunctionsToExport = @(
        'Route',
        'Handler',
        'Tcp',
        'Server',
        'Engine',
        'Html',
        'Json',
        'View',
        'Xml',
        'Pode',
        'Timer',
        'Logger',
        'Csv',
        'Test-IsUnix',
        'Test-IsWindows',
        'Test-IsPSCore',
        'Test-Empty',
        'Status',
        'Redirect',
        'Include',
        'Lock',
        'State',
        'Listen',
        'Access',
        'Limit',
        'Stopwatch',
        'Dispose',
        'Stream',
        'Schedule',
        'Middleware',
        'Endware',
        'Session',
        'Invoke-ScriptBlock',
        'Auth',
        'Attach',
        'Script',
        'Import',
        'Coalesce',
        'Save',
        'Get-PodeConfiguration',
        'Root',
        'Flash',
        'Await',
        'Load',
        'Config',
        'Cookie',
        'Csrf',
        'Gui',
        'Text',
        'File',
        'Header'
    )

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('powershell', 'web', 'server', 'http', 'listener', 'rest', 'api', 'tcp', 'smtp', 'websites',
                'powershell-core', 'windows', 'unix', 'linux', 'pode', 'PSEdition_Core', 'cross-platform', 'access-control',
                'file-monitoring', 'multithreaded', 'rate-limiting', 'cron', 'schedule', 'middleware', 'session',
                'authentication', 'active-directory', 'caching', 'csrf', 'arm', 'raspberry-pi', 'aws-lambda', 'azure-functions')

            # A URL to the license for this module.
            LicenseUri = 'https://raw.githubusercontent.com/Badgerati/Pode/master/LICENSE.txt'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Badgerati/Pode'

            # A URL to an icon representing this module.
            IconUri = 'https://cdn.rawgit.com/Badgerati/Pode/master/images/icon.png'

            # Release notes for this particular version of the module
            ReleaseNotes = 'https://github.com/Badgerati/Pode/releases/tag/v$version$'

        }
    }
}