#
# Internal module manifest for module 'Pode'
#
# Generated by: Matthew Kelly (Badgerati)
#
# Generated on: 24/01/2023
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule        = 'Pode.Internal.psm1'

    # Version number of this module.
    ModuleVersion     = '$version$'

    # ID used to uniquely identify this module
    GUID              = '86b48c1c-8b59-4f3c-80bb-936d6b3218f6'

    # Author of this module
    Author            = 'Matthew Kelly (Badgerati)'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'
}