name: Pode CI - pwsh preview

on:
  push:
    branches:
    - '*'
    - '!gh-pages'
  pull_request:
    branches:
    - '*'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Powershell
      uses: bjompen/UpdatePWSHAction@v1.0.0
      with:
        ReleaseVersion: 'Preview'

    - name: Check PowerShell version
      shell: pwsh
      run: |
        $PSVersionTable.PSVersion

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install Invoke-Build
      shell: pwsh
      run: |
        Install-Module -Name InvokeBuild -RequiredVersion '5.10.5' -Force

    - name: Run Pester Tests
      shell: pwsh
      run: |
        Invoke-Build Test

    - name: Test docker builds
      shell: pwsh
      run: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-Build DockerPack -Version '0.0.0'