name: Pode CI - pwsh 7.4 on windows-latest

on:
  push:
    branches:
    - '*'
    - '!gh-pages'
  pull_request:
    branches:
    - '*'

jobs:
  build:

    runs-on: windows-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install Invoke-Build
      shell: pwsh
      run: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Install-Module -Name InvokeBuild -RequiredVersion '5.10.5' -Force

    # For Windows
    - name: Download and extract PowerShell 7.4
      run: |
        Invoke-WebRequest -Uri "https://github.com/PowerShell/PowerShell/releases/download/v7.4.1/PowerShell-7.4.1-win-x64.zip" -OutFile "PowerShell-7.4.x-win-x64.zip"
        Expand-Archive -LiteralPath "PowerShell-7.4.x-win-x64.zip" -DestinationPath "C:\PowerShell-7.4"

    - name: Check PowerShell version
      run: |
        C:\PowerShell-7.4\pwsh.exe -version

    - name: Run Pester Tests
      run: |
        C:\PowerShell-7.4\pwsh.exe -Command {
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Invoke-Build Test
        }

    - name: Test docker builds
      run: |
        C:\PowerShell-7.4\pwsh.exe -Command {
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Invoke-Build DockerPack -Version '0.0.0'
        }
