name: Pode CI - pwsh 7.5

on:
  push:
    branches:
    - '*'
    - '!gh-pages'
    paths:
    - 'src/**'
    - 'tests/**'
    - 'pode.build.ps1'
    - '.github/workflows/ci-pwsh7_5.yml'
    - 'Dockerfile'
    - '*.dockerfile'
  pull_request:
    branches:
    - '*'
    paths:
    - 'src/**'
    - 'tests/**'
    - 'pode.build.ps1'
    - '.github/workflows/ci-pwsh7_5.yml'
    - 'Dockerfile'
    - '*.dockerfile'

env:
  INVOKE_BUILD_VERSION: '5.12.0'
  POWERSHELL_VERSION: '7.5.0'


jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Setup Powershell - Unix
      shell: pwsh
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        Install-Module -Name InvokeBuild -RequiredVersion $env:INVOKE_BUILD_VERSION -Force
        Invoke-Build SetupPowerShell -PowerShellVersion $env:POWERSHELL_VERSION

    - name: Setup Powershell - Windows
      shell: PowerShell
      if: runner.os == 'Windows'
      run: |
        Install-Module -Name InvokeBuild -RequiredVersion $env:INVOKE_BUILD_VERSION -Force
        Invoke-Build SetupPowerShell -PowerShellVersion $env:POWERSHELL_VERSION

    - name: Output PowerShell version
      shell: pwsh
      run: |
        $PSVersionTable.PSVersion

    - name: Install Invoke-Build
      shell: pwsh
      run: |
        Install-Module -Name InvokeBuild -RequiredVersion $env:INVOKE_BUILD_VERSION -Force

    - name: Run Pester Tests
      shell: pwsh
      run: |
        # Check if the runner is in debug mode
        if ($env:RUNNER_DEBUG -eq '1') {
            $debug = $true
        } else {
            $debug = $false
        }

        if ($debug) {
            Invoke-Build Test -PesterVerbosity Diagnostic
        } else {
            Invoke-Build Test
        }

    - name: Build Packages
      shell: pwsh
      run: |
        Invoke-Build Pack