name: Pode CI - Powershell Desktop

on:
  push:
    branches:
    - '*'
    - '!gh-pages'
    paths:
    - 'src/**'
    - 'tests/**'
    - 'pode.build.ps1'
    - '.github/workflows/ci-powershell.yml'
  pull_request:
    branches:
    - '*'
    paths:
    - 'src/**'
    - 'tests/**'
    - 'pode.build.ps1'
    - '.github/workflows/ci-powershell.yml'

env:
  INVOKE_BUILD_VERSION: '5.12.0'

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Check PowerShell version
      shell: powershell
      run: |
        $PSVersionTable.PSVersion

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Install Invoke-Build
      shell: powershell
      run: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Install-Module -Name InvokeBuild -RequiredVersion $env:INVOKE_BUILD_VERSION -Force

    - name: Run Pester Tests
      shell: powershell
      run: |
        if ([string]::IsNullOrEmpty($env:ACTIONS_STEP_DEBUG)) {
          $debug = $false
        } else {
            $debug = [bool]($env:ACTIONS_STEP_DEBUG -eq 'true')
        }

        if ($debug) {
            Invoke-Build Test -PesterVerbosity Diagnostic
        } else {
            Invoke-Build Test
        }

    - name: Build Packages
      shell: powershell
      run: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-Build Pack