name: VirusTotal Scan - Releases

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check VIRUSTOTAL_API_KEY
      env:
        VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
      run: |
        if [ -z "$VIRUSTOTAL_API_KEY" ]; then
          echo "VIRUSTOTAL_API_KEY is not set. Exiting workflow."
          exit 1
        fi
        echo "VIRUSTOTAL_API_KEY is set. Proceeding with the workflow."

    - name: Run VirusTotal Scan
      uses: crazy-max/ghaction-virustotal@v4
      with:
        vt_api_key: ${{ secrets.VIRUSTOTAL_API_KEY }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        update_release_body: true
        request_rate: 4
        files: |
          .zip$
